import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-brand`}>
        <Navbar />
        {children}
        <footer className="bg-footer-image bg-cover">
          <div className="container mx-auto p-20">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis porro
            cumque molestias facere illo laboriosam pariatur eaque est similique id.
          </div>
      </footer>
      </body>
    </html>
  );
}
